version: "3.9"
services:
  backend:
    build: ./backend
    container_name: finance-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: finance-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
